#!/bin/bash

source config.sh

k=$1

DB_URL="jdbc:mysql://localhost/${DB_PREFIX}_$k"

cd app/build/libs
ln -sf ../../config config
java \
    $OPTIONS \
    -Dserver.port=$(expr $APP_PORT + $k) \
    -Dagent.id=$k \
    -Ddb.url="$DB_URL" \
    -Ddb.username="$DB_USERNAME" \
    -Ddb.password="$DB_PASSWORD" \
    -jar app.jar
